version: "3.7"

services:
  minidlna:
    image: officerjones/minidlna:${VERSION_TAG:-latest}
    restart: unless-stopped
    volumes:
      - /media/nas/movies:/mnt/media/movies
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "192.168.0.14:8200"]
      interval: 1m30s
      timeout: 10s
      retries: 3
